const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">${AIR_ICONS[name]||AIR_ICONS.arrow}</svg>`;
let previousNav=0;
const A='../assets/';
const wines=[
  {name:'Красностоп',winery:'Демо-винодельня',year:'2022',kind:'Красное сухое',abv:'13,5%',image:'demo-krasnostop-2022.svg'},
  {name:'Каберне Фран',winery:'Виноградный берег',year:'2019',kind:'Красное полусухое',abv:'',image:'demo-cabernet-franc-2019.svg'},
  {name:'Пино Нуар',winery:'Тихая долина',year:'2020',kind:'Красное сухое',abv:'12,5%',image:'demo-pinot-noir-2020.svg'},
  {name:'Шираз',winery:'Солнечный склон',year:'2021',kind:'Красное полусухое',abv:'',image:'demo-shiraz-2021.svg'},
  {name:'Саперави',winery:'Винный дом',year:'',kind:'Красное сухое',abv:'13%',image:'demo-saperavi-no-year.svg'}
];
const scenarioNames={home:'Главная',capture:'Камера',loading:'Распознавание',slow:'Долгий поиск',results:'Похожие вина',detail:'Карточка вина',notfound:'Ничего не найдено',server:'Ошибка сервера',offline:'Нет сети',search:'Поиск по названию',saved:'Сохранённое'};
const rationales={home:'Новый вход всегда чистый: прежний снимок и запрос не появляются на Главной. Пункт навигации отменяет текущий демо-поиск.',capture:'Камера показана как симуляция. Физический доступ к устройству не запрашивается; снимок служит только переходом по макету.',loading:'Собака остаётся в сцене среди винных полок. Линия сканирования движется только внутри миниатюры снимка.',slow:'При долгом ответе сцена собаки сохраняется. Движение линии ограничено снимком и отключается настройкой сокращения анимации.',results:'Ваш снимок компактный, расположен слева и открывается без потери списка. Камера и галерея доступны рядом.',detail:'Карточка отдаёт место бутылке и названию. Год и крепость показаны только при наличии в демо-данных; цвет отдельно не дублируется.',notfound:'Успешный ответ без совпадений — отдельный исход. Первое действие ведёт к поиску по названию; ниже остаются камера и галерея.',server:'Сервер не ответил корректно. Первое действие — повторить поиск с тем же снимком; новый снимок можно выбрать камерой или галереей.',offline:'Проблема подключения показана отдельно от серверной ошибки. Пользователь может повторить запрос с тем же снимком.',search:'Поиск по названию не притворяется распознаванием фотографии. Результаты берутся из маленького синтетического списка.',saved:'Сохранение показано локально для проверки перехода. Это состояние не связано с реальным аккаунтом или каталогом.'};
const state={screen:'home',photo:false,origin:'results',selected:0,savedIds:new Set(),searchValue:'',searchSubmitted:false,modal:null,fixture:'clear',request:0,serverVariant:'a',captureOrigin:'home',returnScroll:null,notfoundReason:'empty'};
let timers=[];
// Editorial facts with sources in waiting-notes.md; not attributed quotations.
const wineNotes=[
 'Белое вино тоже можно сделать из тёмного винограда.',
 'Пузырьки шампанского рождаются при втором брожении в бутылке.',
 'Красное вино обычно получает цвет от кожицы винограда.',
 'Дубовая бочка может подарить вину аромат ванили.',
 'Оранжевому вину цвет даёт кожица белого винограда.',
 'Розовое вино получает цвет при коротком контакте с кожицей.',
 'У Сира бывает аромат чёрного перца — без добавления специй.',
 'В аромате Муската можно узнать свежий виноград.',
 'Прохладный климат помогает сохранить кислотность винограда.',
 'Созревая, виноград накапливает сахар и теряет кислотность.',
 'Брожение рождает новые ароматы, которых не было в винограде.',
 'Дуб меняет характер вина, но не гарантирует его качество.'
];
function shuffledNotes(previous,random=Math.random){
 const order=wineNotes.map((_,i)=>i);
 for(let i=order.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}
 if(order.length>1&&order[0]===previous){const j=1+Math.floor(random()*(order.length-1));[order[0],order[j]]=[order[j],order[0]]}
 return order;
}
let noteOrder=[],noteCursor=0,noteIndex=-1,notesPaused=false,noteInterval=null,noteSwapTimer=null;
function resetNotes(){stopNotes();noteOrder=shuffledNotes(noteIndex);noteCursor=0;noteIndex=noteOrder[0]}
function nextNote(){if(++noteCursor===noteOrder.length){noteOrder=shuffledNotes(noteIndex);noteCursor=0}noteIndex=noteOrder[noteCursor]}
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
function stopNotes(){clearInterval(noteInterval);clearTimeout(noteSwapTimer);noteInterval=null;noteSwapTimer=null;document.querySelector('.wine-note-copy')?.classList.remove('is-changing')}
function syncNotes(){
 const active=['loading','slow'].includes(state.screen);
 if(!active||notesPaused||reducedMotion.matches||document.hidden||state.modal==='photo'){stopNotes();return}
 if(noteInterval)return;
 noteInterval=setInterval(()=>{
  const copy=document.querySelector('.wine-note-copy');if(!copy)return;
  copy.classList.add('is-changing');
  noteSwapTimer=setTimeout(()=>{if(!copy.isConnected)return;nextNote();copy.textContent=wineNotes[noteIndex];copy.classList.remove('is-changing')},350);
 },8000);
}
function toggleNotes(){notesPaused=!notesPaused;const button=document.querySelector('.note-pause');if(button){button.innerHTML=icon(notesPaused?'play':'pause');button.setAttribute('aria-label',notesPaused?'Продолжить смену заметок':'Приостановить смену заметок');button.title=button.getAttribute('aria-label');button.setAttribute('aria-pressed',String(notesPaused))}syncNotes()}
reducedMotion.addEventListener('change',syncNotes);
document.addEventListener('visibilitychange',syncNotes);
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(file,alt='',cls='')=>`<img class="${cls}" src="${A+file}" alt="${esc(alt)}">`;
function iconSvg(mark){return icon(({ '◎':'camera','▧':'gallery','⌕':'search','⌂':'home','♡':'bookmark','♥':'bookmark','↻':'retry','→':'arrow','↗':'external'})[mark]||mark)}
function btn(label,action,style='primary',icon=''){return `<button class="btn ${style}" data-action="${action}">${icon?`<span class="btn-icon">${iconSvg(icon)}</span>`:''}<span>${label}</span></button>`}
function screenHeader(title,back='home'){return `<header class="app-top"><button class="back" data-action="return:${back}" aria-label="Назад">${icon('back')}</button><span>${title}</span><i aria-hidden="true"></i></header>`}
function actions(){return `<div class="dual-actions">${btn('Камера','capture','secondary','◎')}${btn('Галерея','gallery','secondary','▧')}</div>`}
function nav(){let active=state.screen==='home'?'home':(state.screen==='saved'||state.screen==='detail'&&state.origin==='saved')?'saved':'search';let current={home:0,search:1,saved:2}[active];let from=previousNav;previousNav=current;return `<nav class="bottom-nav" aria-label="Основная навигация"><span class="nav-slider" data-from="${from}" data-to="${current}" aria-hidden="true" style="transform:translateX(${from*100}%)"></span><button class="${active==='home'?'active':''}" data-action="home">${icon('home')}Главная</button><button class="${active==='search'?'active':''}" data-action="search">${icon('search')}Поиск</button><button class="${active==='saved'?'active':''}" data-action="saved">${icon('bookmark')}Сохранённое</button></nav>`}
function dog(file,cls=''){return img(file,'Иллюстрация собаки-детектива',`dog ${cls}`)}
function photo(cls='',fixture=state.fixture){return `<div class="photo-visual ${cls} ${fixture==='blur'?'alternate':''}"><div class="photo-bottle">${img(fixture==='blur'?'demo-cabernet-franc-2019.svg':'demo-krasnostop-2022.svg','Демонстрационная этикетка')}</div><span class="photo-grain"></span></div>`}
function captureCard(){return `<div class="camera-frame"><div class="camera-corners"></div>${photo('camera-photo','clear')}<div class="camera-caption">Поместите этикетку в рамку</div></div>`}
function renderScreen(){switch(state.screen){
case 'home':return `<div class="home-screen"><div class="brand">${img('svoe-vino-logo.svg','Своё Вино','brand-logo')}</div><div class="home-hero"><h2>Какое вино<br>перед вами?</h2><p>Сфотографируйте этикетку. Откроем карточку вина.</p><div class="hero-dog">${dog('mascot-hold-2d-alpha.webp')}</div></div><div class="home-actions"><button class="home-scan" data-action="capture"><span class="home-scan-icon">${icon('camera')}</span><span class="home-scan-copy"><b>Сканировать вино</b></span><span class="home-scan-target">${icon('scan')}</span></button><div class="home-secondary">${btn('Выбрать фото','gallery','text','▧')}${btn('По названию','search','text','⌕')}</div></div></div>`;
case 'capture':return `<div class="capture-immersive camera-simple">${screenHeader('Этикетка вина',state.captureOrigin)}<section class="screen-content capture-screen"><p class="capture-guidance">Нужная бутылка по центру</p>${captureCard()}<div class="camera-controls"><button class="camera-gallery" data-action="gallery" aria-label="Выбрать фото из галереи">${icon('gallery')}</button><button class="camera-shutter" data-action="scan" aria-label="Сделать снимок"><span></span></button><span aria-hidden="true"></span></div></section></div>`;
case 'loading':case 'slow':return `${screenHeader('Поиск по фото','cancel')}<section class="screen-content progress-screen"><h2>${state.screen==='slow'?'Нужно ещё<br>немного времени':'Ищем ваше вино'}</h2><p class="subcopy">${state.screen==='slow'?'Проверяем похожие записи в каталоге.':'Сверяем снимок с винами в каталоге.'}</p><div class="progress-composition"><div class="progress-dog">${dog(state.screen==='slow'?'mascot-walk-2d-alpha.webp':'mascot-cellar-2d-alpha.webp')}</div></div><div class="waiting-discovery"><button class="scan-photo" data-action="photo" aria-label="Открыть ваш снимок">${photo()}<span class="scan-line" aria-hidden="true"></span></button><aside class="wine-note" aria-label="Заметка о вине" aria-live="off"><div class="wine-note-top"><span>О вине</span><button class="note-pause" data-action="toggle-notes" aria-label="${notesPaused?'Продолжить смену заметок':'Приостановить смену заметок'}" title="${notesPaused?'Продолжить смену заметок':'Приостановить смену заметок'}" aria-pressed="${notesPaused}">${icon(notesPaused?'play':'pause')}</button></div><p class="wine-note-copy">${wineNotes[noteIndex]}</p></aside></div><div class="scan-status waiting-status" role="status"><span class="spinner" aria-hidden="true"></span>${state.screen==='slow'?'Поиск ещё идёт':'Ищем в каталоге'}</div><div class="flex-spacer"></div>${btn('Отменить поиск','cancel','text')}</section>`;
case 'results':return `${screenHeader('Результат поиска','home')}<section class="screen-content results-screen"><h2>Нашли похожие вина</h2><p class="subcopy">Сравните название и винодельню.</p><div class="comparison-row"><button class="origin-thumb" data-action="photo" aria-label="Открыть ваш снимок">${photo()}<span>Ваше фото</span></button><div class="comparison-actions" role="group" aria-label="Заменить снимок"><button class="photo-action" data-action="capture" aria-label="Сделать новый снимок" title="Сделать новый снимок">${icon('camera')}</button><button class="photo-action" data-action="gallery" aria-label="Выбрать фото из галереи" title="Выбрать фото из галереи">${icon('gallery')}</button></div></div><div class="candidate-list">${wines.map((w,i)=>`<button class="candidate ${i===0?'leader':''}" data-action="detail:${i}">${i===0?'<span class="leader-label">Наиболее похожее</span>':''}${img(w.image,'Демонстрационная бутылка')}<span class="candidate-info"><small>${w.winery}</small><strong>${w.name}${w.year?` <span class="candidate-year">${w.year}</span>`:''}</strong><span class="candidate-meta"><em>${w.kind}</em>${w.abv?`<em>${w.abv}</em>`:''}</span></span><span class="candidate-arrow">${icon('arrow')}</span></button>`).join('')}</div><button class="inline-link" data-action="notfound">Ни одно вино не подходит <span>${icon('external')}</span></button></section>`;
case 'detail':{let w=wines[state.selected];return `${screenHeader('Карточка вина',state.origin)}<section class="screen-content detail-screen"><div class="eyebrow">ДЕМОНСТРАЦИОННАЯ КАРТОЧКА</div><div class="detail-hero"><div class="bottle-pedestal">${img(w.image,'Демонстрационная бутылка')}</div><div class="detail-lead"><small>${w.winery}</small><h2>${w.name}</h2></div></div><div class="detail-facts"><div><span>Тип</span><strong>${w.kind}</strong></div>${w.year?`<div><span>Год</span><strong>${w.year}</strong></div>`:''}${w.abv?`<div><span>Крепость</span><strong>${w.abv}</strong></div>`:''}</div><p class="detail-disclaimer">Данные и бутылка созданы для демонстрации интерфейса.</p><div class="flex-spacer"></div>${btn(state.savedIds.has(state.selected)?'Сохранено':'Сохранить вино',state.savedIds.has(state.selected)?'unsave':'save',state.savedIds.has(state.selected)?'secondary':'primary',state.savedIds.has(state.selected)?'♥':'♡')}${state.photo&&state.origin==='results'?btn('Сверить с моим фото','photo','text','▧'):''}</section>`}
case 'notfound':return `${screenHeader('Поиск по фото')}<section class="screen-content empty-screen"><div class="eyebrow">${state.notfoundReason==='rejected'?'ВАРИАНТЫ НЕ ПОДОШЛИ':'СОВПАДЕНИЙ НЕТ'}</div><div class="state-dog counter">${dog('mascot-counter-thoughtful-2d-alpha.webp')}</div><h2>${state.notfoundReason==='rejected'?'Ни один вариант<br>не подошёл':'Пока не нашли<br>это вино'}</h2><p class="subcopy">${state.notfoundReason==='rejected'?'Попробуйте найти вино по названию или снять другую сторону этикетки.':'Попробуйте название или снимите этикетку ещё раз.'}</p><div class="flex-spacer"></div>${btn('Найти по названию','search','primary','⌕')}${actions()}</section>`;
case 'server':return `${screenHeader('Поиск по фото')}<section class="screen-content empty-screen"><div class="eyebrow">ОШИБКА СЕРВИСА</div><div class="state-dog server">${dog(`server-error-${state.serverVariant}.png`)}</div><h2>Не удалось<br>получить ответ</h2><p class="subcopy">Сервис не смог завершить поиск. Попробуйте ещё раз — фото загружать заново не нужно.</p><div class="flex-spacer"></div>${btn('Повторить поиск','retry','primary','↻')}${actions()}</section>`;
case 'offline':return `${screenHeader('Поиск по фото')}<section class="screen-content empty-screen"><div class="eyebrow">НЕТ ПОДКЛЮЧЕНИЯ</div><div class="state-dog offline">${dog('mascot-offline-2d-alpha.webp')}</div><h2>Похоже, нет сети</h2><p class="subcopy">Подключитесь к интернету и попробуйте снова.</p><div class="flex-spacer"></div>${btn('Проверить ещё раз','retry','primary','↻')}${actions()}</section>`;
case 'search':return `${screenHeader('Поиск по названию')}<section class="screen-content search-screen"><div class="eyebrow">РУЧНОЙ ПОИСК</div><h2>Найдём<br>по названию</h2><p class="subcopy">Введите вино или винодельню.</p><form id="search-form"><label for="wine-query">Название вина</label><div class="search-input"><span>${icon('search')}</span><input id="wine-query" name="query" autocomplete="off" placeholder="Например, Красностоп" value="${esc(state.searchValue)}"><button aria-label="Искать" type="submit">${icon('arrow')}</button></div></form>${state.searchSubmitted?`<p class="list-title">Демонстрационные результаты</p><div class="candidate-list">${wines.filter(w=>!state.searchValue||`${w.name} ${w.winery}`.toLowerCase().includes(state.searchValue.toLowerCase())).map(w=>`<button class="candidate" data-action="detail:${wines.indexOf(w)}">${img(w.image,'Демонстрационная бутылка')}<span class="candidate-info"><small>${w.winery}</small><strong>${w.name}</strong><em>${w.kind}${w.year?' · '+w.year:''}</em></span><span class="candidate-arrow">${icon('arrow')}</span></button>`).join('')||'<p class="no-query">В демонстрационном каталоге совпадений нет.</p>'}</div>`:`<button class="search-hint" data-action="search-demo">Попробовать «Каберне» <span>${icon('external')}</span></button>`}${!state.searchSubmitted?`<div class="search-mascot" aria-hidden="true">${dog('mascot-cellar-2d-alpha.webp')}</div>`:''}<div class="flex-spacer"></div>${btn('Сканировать этикетку','capture','text','◎')}</section>`;
case 'saved':return `${screenHeader('Сохранённое')}<section class="screen-content saved-screen"><div class="eyebrow">ВАША ПОЛКА</div><h2>Сохранённое</h2>${state.savedIds.size?`<div class="candidate-list saved-list">${[...state.savedIds].map(i=>{const w=wines[i];return `<button class="candidate" data-action="detail:${i}">${img(w.image,'Демонстрационная бутылка')}<span class="candidate-info"><small>${w.winery}</small><strong>${w.name}</strong><em>${w.kind}</em></span><span class="candidate-arrow">${icon('arrow')}</span></button>`}).join('')}</div>`:`<div class="saved-empty">${dog('mascot-hold-2d-alpha.webp')}<p>Здесь появятся вина, которые вы сохраните из карточки.</p></div>`}<div class="flex-spacer"></div>${btn('Найти вино','capture','primary','◎')}</section>`;
}}
function render(){const refocusNote=document.activeElement?.matches('.note-pause');let screen=app.querySelector('#screen-stage');if(!screen){app.innerHTML='<div id="screen-stage"></div>'+nav();screen=app.querySelector('#screen-stage')}screen.innerHTML=renderScreen();const current=state.screen==='home'?0:(state.screen==='saved'||state.screen==='detail'&&state.origin==='saved')?2:1;app.querySelectorAll('.bottom-nav button').forEach((b,i)=>{b.classList.toggle('active',i===current);if(i===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});const indicator=app.querySelector('.nav-slider');if(indicator){indicator.dataset.to=current;indicator.style.transform=`translateX(${current*100}%)`};app.classList.toggle('camera-open',state.screen==='capture');syncNotes();if(refocusNote)app.querySelector('.note-pause')?.focus({preventScroll:true});document.querySelector('#state-name').textContent=scenarioNames[state.screen];document.querySelector('#state-rationale').textContent=state.screen==='notfound'&&state.notfoundReason==='rejected'?'Пользователь отверг предложенные бутылки. Следующий путь — ручной поиск или новый снимок; это не означает пустой ответ каталога.':rationales[state.screen];const slider=app.querySelector('.nav-slider');if(slider){slider.getBoundingClientRect();requestAnimationFrame(()=>{slider.style.transform=`translateX(${slider.dataset.to*100}%)`})}document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('is-active',b.dataset.scenario===state.screen));}
function stopRequest(){state.request++;timers.forEach(clearTimeout);timers=[];}
function go(screen){if(['loading','slow'].includes(screen)&&!['loading','slow'].includes(state.screen))resetNotes();if(screen==='home'){stopRequest();state.photo=false;state.origin='results';state.fixture='clear';state.captureOrigin='home';state.modal=null;closeDialog();}else if(!['loading','slow'].includes(screen))stopRequest();const returning=state.screen==='detail'&&screen===state.origin;const savedScroll=returning?state.returnScroll:null;state.screen=screen;const url=new URL(window.location.href);url.searchParams.set('screen',screen);history.replaceState(null,'',url);render();app.scrollTop=0;document.querySelector('#phone').scrollTop=0;requestAnimationFrame(()=>{if(savedScroll){document.querySelector('#phone').scrollTop=savedScroll.phone;if(window.innerWidth<=900)window.scrollTo({top:savedScroll.window,behavior:'instant'})}else if(window.innerWidth<=900){const area=document.querySelector('.phone-area');window.scrollTo({top:area.getBoundingClientRect().top+window.scrollY,behavior:'instant'})}});}
function scan(source='camera'){stopRequest();if(state.screen==='capture'&&source!=='gallery')state.fixture='clear';state.photo=true;go('loading');const id=state.request;timers.push(setTimeout(()=>{if(id===state.request&&state.screen==='loading')go('slow')},5000));timers.push(setTimeout(()=>{if(id===state.request&&['loading','slow'].includes(state.screen))go('results')},11000));}
function openFixture(){const root=document.querySelector('#dialog-root');root.innerHTML=`<div class="dialog-scrim" data-action="close-dialog"><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button class="dialog-close" data-action="close-dialog" aria-label="Закрыть">${icon('close')}</button><div class="eyebrow">СИМУЛЯЦИЯ ГАЛЕРЕИ</div><h2 id="dialog-title">Выберите демо-снимок</h2><p>Файлы с устройства не открываются и не передаются.</p><button class="fixture-option" data-action="fixture:clear">${photo('','clear')}<span><strong>Чёткая этикетка</strong><small>Показать поиск по снимку</small></span><span>${icon('external')}</span></button><button class="fixture-option" data-action="fixture:blur">${photo('','blur')}<span><strong>Другой ракурс</strong><small>Показать поиск по снимку</small></span><span>${icon('external')}</span></button></div></div>`;root.querySelector('.dialog-close').focus();}
function openPhoto(){if(!state.photo)return;state.modal='photo';syncNotes();const root=document.querySelector('#dialog-root');root.innerHTML=`<div class="dialog-scrim" data-action="close-dialog"><div class="dialog photo-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button class="dialog-close" data-action="close-dialog" aria-label="Закрыть">${icon('close')}</button><div class="eyebrow">ВАШ СНИМОК</div><h2 id="dialog-title">Ваш снимок</h2>${photo('modal-photo')}<button class="btn primary" data-action="close-dialog">Вернуться к ${state.screen==='results'?'вариантам':['loading','slow'].includes(state.screen)?'поиску':'карточке'}</button></div></div>`;root.querySelector('.dialog-close').focus();}
function closeDialog(){document.querySelector('#dialog-root').innerHTML='';state.modal=null;syncNotes();}
function action(a){if(a.startsWith('return:')){const target=a.slice(7);go(target==='cancel'?'home':target);return}if(a.startsWith('detail:')){state.selected=+a.split(':')[1];state.origin=state.screen==='search'?'search':state.screen==='saved'?'saved':'results';state.returnScroll={phone:document.querySelector('#phone').scrollTop,window:window.scrollY};go('detail');return}if(a.startsWith('fixture:')){state.fixture=a.split(':')[1];closeDialog();scan('gallery');return}if(a.startsWith('server-variant:')){state.serverVariant=a.split(':')[1];document.querySelectorAll('.variant-options button').forEach(b=>{let selected=b.dataset.action===a;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)});go('server');return}switch(a){case 'toggle-notes':toggleNotes();break;case 'home':go('home');break;case 'capture':state.captureOrigin=state.screen==='capture'?state.captureOrigin:state.screen;go('capture');break;case 'gallery':openFixture();break;case 'scan':case 'retry':scan();break;case 'cancel':go('home');break;case 'photo':openPhoto();break;case 'close-dialog':closeDialog();break;case 'save':state.savedIds.add(state.selected);render();break;case 'unsave':state.savedIds.delete(state.selected);render();break;case 'notfound':state.notfoundReason='rejected';go('notfound');break;case 'search-demo':state.searchValue='Каберне';state.searchSubmitted=true;render();break;default:if(scenarioNames[a]){if(['loading','slow','results','detail','notfound','server','offline'].includes(a))state.photo=true;if(a==='detail'){state.selected=0;state.origin='results'}if(a==='notfound')state.notfoundReason='empty';if(a==='capture')state.captureOrigin='home';go(a)}}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-scenario],[data-width]');if(!el)return;if(el.classList.contains('dialog-scrim')&&e.target!==el)return;e.preventDefault();if(el.dataset.width){document.documentElement.style.setProperty('--phone-width',`${el.dataset.width}px`);document.querySelectorAll('[data-width]').forEach(b=>{const selected=b===el;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)});return}if(el.dataset.scenario==='notfound'){state.notfoundReason='empty';state.photo=true;go('notfound')}else if(el.dataset.scenario)action(el.dataset.scenario);else action(el.dataset.action)});
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();state.searchValue=e.target.querySelector('input').value.trim();state.searchSubmitted=true;render()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDialog()});
const groups=[['Начало',['home','capture','loading','slow']],['Ответ',['results','detail','notfound']],['Восстановление',['server','offline','search','saved']]];
document.querySelector('#scenario-list').innerHTML=groups.map(([label,items])=>`<div class="scenario-group"><div class="scenario-label">${label}</div>${items.map(id=>`<button data-scenario="${id}"><span>${scenarioNames[id]}</span><span>${icon('external')}</span></button>`).join('')}</div>`).join('');
const initialScreen=new URLSearchParams(window.location.search).get('screen');if(initialScreen&&Object.hasOwn(scenarioNames,initialScreen)){if(['loading','slow','results','detail','notfound','server','offline'].includes(initialScreen))state.photo=true;if(initialScreen==='detail')state.origin='results';go(initialScreen)}else render();
